name: sw

on:
  push:
    paths:
      - 'source/**'
      - '.github/workflows/sw.yml' # for test purposes
  pull_request:
    paths:
      - 'source/**'
      - '.github/workflows/sw.yml' # for test purposes

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - uses: egorpugin/sw-action@master
    - run: ./sw build org.sw.demo.perl.perl
    - name: build
      run: ./sw build source -static
    #- name: test
      #run: ./sw test source
    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: sw-windows
        path: .sw/out
